### PR TITLE
Trending videos per region

### PR DESCRIPTION
**Pull request by VivianoRiccardo**
I added a feature for trending videos per region, i used another base url found on another github repo, i tried with the base url you provided but i think the only way to get trending videos by region with your base url is with proxy servers. (don't look at the commits look at the file changes)

### CODE REVIEW

**Comment by demon071** [comment]
Yes, I also think so, you can use a proxy to get other country data

**Comment by VivianoRiccardo** [comment]
The code i provide doesn t need proxy server.

**Comment by demon071** [comment]
Does it work?

**Comment by VivianoRiccardo** [comment]
Yes

**Comment by demon071** [comment]
Yes, I have tried it and it works in all api, if you want to get trending region you must use a proxy

**Pull request closed without merging**
